<a href="https://colab.research.google.com/github/jjcruzado/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors:
- a torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
- default datatype is float32

In [2]:
import torch
import numpy as np

Lists

In [4]:
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

Numpy array

In [5]:
np1 = np.random.rand(3,4)
np1

array([[0.99410786, 0.14825947, 0.77832467, 0.69816231],
       [0.01354977, 0.29858352, 0.59375491, 0.51885866],
       [0.72204045, 0.70902726, 0.64518893, 0.17992936]])

In [6]:
np1.dtype

dtype('float64')

Tensors

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7372,  0.9303,  1.0773, -0.7096],
        [ 1.5840,  1.0806,  0.4503, -3.4193],
        [-0.3549, -2.3724, -2.5029, -0.3571]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9941, 0.1483, 0.7783, 0.6982],
        [0.0135, 0.2986, 0.5938, 0.5189],
        [0.7220, 0.7090, 0.6452, 0.1799]], dtype=torch.float64)

the default type above is float64 is because the default type of the numpy array is float64